### ISSUE TITLE
Assignment 8 submission

### ISSUE THREAD

**Issue by e-bish** [e-bish/Assignment-8#1]
Hi Mark! I created a presentation about what I learned this quarter. Thanks for the fun class!

**Comment by mdscheuerell** [comment]
Well done, Emily. I'm glad you enjoyed the class.
> 3. Group work (it would be fun in the future to have us work in teams on some repos to practice collaborative work, branching, and resolving conflicts!)

And this is a great idea—it's something I've been thinking about as well.
